import ScPatternSelect

patt_sel = ScPatternSelect.ScPatternSelect("SYS0", "1", "sioc-sys0-ts01")
print("testing SCPatternGlobals")
print("testing class variables")
print(f"DEST_NAMES: {patt_sel.globals.DEST_NAMES}")
print(f"TYPE_DICT: {patt_sel.globals.TYPE_DICT}")
print(f"BSYD_FALLBACK_ENG: {patt_sel.globals.BSYD_FALLBACK_ENG}")
print(f"RATE_SFX: {patt_sel.globals.RATE_SFX}")
print(f"TSOURCE_SFX: {patt_sel.globals.TSOURCE_SFX}")
print(f"BUNCHES_PER_TRAIN_SFX: {patt_sel.globals.BUNCHES_PER_TRAIN_SFX}")
print(f"BUNCH_SPACING_SFX: {patt_sel.globals.BUNCH_SPACING_SFX}")
print(f"OFFSET_SFX: {patt_sel.globals.OFFSET_SFX}")
print(f"PATTERN_TYPE: {patt_sel.globals.PATTERN_TYPE}")
print(f"PATTERN_TYPES: {patt_sel.globals.PATTERN_TYPES}")
print(f"PATTERN_KEYS: {patt_sel.globals.PATTERN_KEYS}")
print(f"PATTERN_KEYS_DISPLAYED: {patt_sel.globals.PATTERN_KEYS_DISPLAYED}")
print(f"MODES: {patt_sel.globals.MODES}")

print("\nTesting class functions")
print(f"get_patt_table_name: {patt_sel.globals.get_patt_table_name()}")
print(f"get_mode_table_name: {patt_sel.globals.get_mode_table_name()}")
print(f"get_tag_table_name: {patt_sel.globals.get_tag_table_name()}")
print(f"get_timing_sources, default: {patt_sel.globals.get_timing_sources()}")
print(f"get_timing_sources, with any: {patt_sel.globals.get_timing_sources(True)}")
print(f"get_tpg_base_pv: {patt_sel.globals.get_tpg_base_pv()}")
print(f"get_mode_pv: {patt_sel.globals.get_mode_pv()}")
print(f"get_path_set_pv: {patt_sel.globals.get_path_set_pv()}")
print(f"get_load_pv: {patt_sel.globals.get_load_pv()}")
print(f"get_apply_pv: {patt_sel.globals.get_apply_pv()}")
print(f"get_TpgPatternSetup_top: {patt_sel.globals.get_TpgPatternSetup_top()}")
print(f"get_pattern_top: {patt_sel.globals.get_pattern_top()}")
print(f"get_verified_patt_path: {patt_sel.globals.get_verified_patt_path()}")
print(f"get_test_patt_path: {patt_sel.globals.get_test_patt_path()}")
print(
    f"get_meta_data_path, verified: {patt_sel.globals.get_meta_data_path('test_pattern_name', True)}"
)
print(
    f"get_meta_data_path, test: {patt_sel.globals.get_meta_data_path('test_pattern_name', False)}"
)
print(f"get_tag_path: {patt_sel.globals.get_tag_path()}")
print(f"get_report_top: {patt_sel.globals.get_report_top()}")
print(f"Test of SCPatternGlobals complete")
